version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-redis-network

  celery:
    build: .
    command: sh -c "celery -A weather worker -l info"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      CELERY_BROKER: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - my-redis-network

networks:
  my-redis-network: